<?php
/**
 * @file
 * Code for the Landportal Partners module
 */

include_once 'landportal_partners.features.inc';
include_once 'landportal_partners.block.inc';
include_once 'landportal_partners.context.inc';

function landportal_partners_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}


// Show
// Add block descriptions to Partners header menu
function landportal_partners_preprocess(&$variables, $hook) {
  //if ($hook == 'block') dsm($variables, $hook);
}

// Show
// Add block descriptions to Partners header menu
function landportal_partners_preprocess_page(&$variables) {
  if (@$variables['page']['header']) {
    $pheader = $variables['page']['header'];
    /* if (isset($pheader['og_menu_og_single_menu_block'])) { */
    /*   $i = 'og_menu_og_single_menu_block'; */
    /*     $menu = menu_load($i); */
    /*     //$desc = i18n_string_translate('menu:menu:'.$i.':description', $menu['description']); */
    /*     $pheader[$i]['#block']->description = $menu['description']; */
    /*     //dpm($menu); */
    /*     //dpm($variables, $i); */
    /* } */
    foreach (array('menu-partners-mlike', 'menu-legend', 'menu-squatting-conflicts') as $i) {
      if (isset($pheader['menu_'.$i]) && $pheader['menu_'.$i]) {
        $menu = menu_load($i);
        $desc = i18n_string_translate('menu:menu:'.$i.':description', $menu['description']);
        $pheader['menu_'.$i]['#block']->description = $desc;
      }
    }
  }
}



/**
 * Implements hook_views_default_views().
 */
function landportal_partners_views_default_views() {
    $export = array();

    $path = drupal_get_path('module', 'landportal_partners').'/views';
    $files = file_scan_directory($path, '/\.inc$/');
    foreach ($files as $filepath => $file) {
      include_once $filepath;
      $export[$view->name] = $view;
    }
    return $export;
}

function landportal_partners_views_post_render(&$view, &$output, &$cache) {
  if ( ! ($view->name == 'partners_content' && $view->current_display == 'related') ) return;
  $jsnew = "<script>(function($) { $(document).ready(function() {
  $('.view-id-partners_content.view-display-id-related article a[href]').attr({ target: '_blank' })
}); }(jQuery));</script>";
  $output .= $jsnew;
}

/**
 * Implements hook_element_info_alter().
 *
 * Add callback to inject body class.
 * See hook_field_widget_form_alter
 */
function landportal_partners_element_info_alter(&$types) {
  // Used when using ckeditor module.
  if (isset($types['text_format']['#pre_render']) && is_array($types['text_format']['#pre_render'])) {
    if (in_array('ckeditor_pre_render_text_format', $types['text_format']['#pre_render'])) {
      $types['text_format']['#pre_render'][] = 'landportal_partners_pre_render_ckeditor_element';
      $types['text_format']['#attached']['js'][] = array(
        'data' => drupal_get_path('module', 'landportal_partners') . '/ckeditor.js',
        'type' => 'file',
        'scope' => 'footer',
        'weight' => 30,
      );
    }
  }
}

/**
 * Implements hook_field_widget_form_alter().
 *
 * Add partners OG id / page info to CKE body class
 */
// FROM http://cgit.drupalcode.org/sandbox-rudiedirkx-2454217
function landportal_partners_pre_render_ckeditor_element($element) {
  if (!isset($element['#entity'])) {
    return $element;
  }
  $entity = $element['#entity'];
  //dpm($element, 'cke element');
  if (!isset($element['#attributes']['data-ckeditor-body-classes'])) {
    $element['#attributes']['data-ckeditor-body-classes'] = '';
  }
  if (isset($entity->og_group_ref)) {
    $element['#attributes']['data-ckeditor-body-classes'] .=
      ' og-context-node-' . $entity->og_group_ref[LANGUAGE_NONE][0]['target_id'];
  } else if (isset($entity->type) && $entity->type == 'partners') {
    $element['#attributes']['data-ckeditor-body-classes'] .= ' og-context-node-' . $entity->nid;
  /* } else { */
  /*   dpm($element); */
  }
  return $element;
}
