<?php
/**
 * @file
 * Code for the Landportal Partners module
 */

include_once 'landportal_partners.features.inc';
include_once 'landportal_partners.block.inc';
include_once 'landportal_partners.context.inc';

function landportal_partners_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_views_default_views().
 */
function landportal_partners_views_default_views() {
    $export = array();
    include 'views/partners_content.inc';
    $export[$view->name] = $view;
    return $export;
}
