<?php
/**
 * @file
 * Code for the Landportal field display feature.
 */

include_once 'landportal_display.features.inc';

/*
 * Implement hook_entity_info_alter().
 */
function landportal_display_entity_info_alter(&$entity_info){
  $entity_info['node']['view modes']['listing'] = array(
    'label' => t('Listing'),
    'custom settings' => TRUE,
  );
}


/******************************************
 *
 * CKEditor
 */
// Override CKeditor JS
function landportal_display_ckeditor_settings_alter(&$settings, $context) {
  //dpm($context);
  $path = drupal_get_path('module', 'landportal_display');
  drupal_add_js(array('landportal_cke' => array('path' => $path)), 'setting');
  $settings['stylesCombo_stylesSet'] = "default:/" . $path . "/ckeditor.styles.js";
  $settings['contentsCss'][] = "/" . drupal_get_path('theme', 'lpbs') . "/css/lp-bootstrap.css";
  $settings['contentsCss'][] = "/" . drupal_get_path('theme', 'lpbs') . "/css/style.css";
}



/******************************************
 *
 * Hacks for drupal page headers (title)
 *
 * Maybe this should be back in theme as this is pretty much appearence related and will only work nicely with LPBS theme
 */
function landportal_display_preprocess_page(&$variables) {
  $sysmain = &$variables['page']['content']['system_main'];
  // Taxonomy term page
  if (array_key_exists('term_heading', $sysmain)) {
    $term = &$sysmain['term_heading']['term'];
    if (@$header = landportal_display__get_header($term)) {
      //dpm($header);
      $variables['title_group'] = $header;
      $variables['title'] = render($header);
    }
    // For Tax. term pages without a header group
    else if (@isset($term['name_field'])) {
      $variables['title'] = render($term['name_field']);
      unset($term['name_field']);
    }
  }
  // Node page
  else if (array_key_exists('nodes', $sysmain)) {
    $first = array_keys($sysmain['nodes'])[0];
    $node = &$sysmain['nodes'][$first];
    if (@$header = landportal_display__get_header($node)) {
      $variables['title_group'] = $header;
      $variables['title'] = render($header);
    }
  }
  else {
    // Wrap page title in an h1
    //$variables['title'] = '<h1>' . $variables['title'] . '</h1>';
  }
  //dpm($variables);
}

// Pick group_header if it exists, return it and suppress it from content
function landportal_display__get_header(&$content) {
  if (isset($content['#fieldgroups']) && isset($content['#fieldgroups']['group_header'])) {
    $header = $content['#fieldgroups']['group_header'];
    $header = landportal_display_extract_groups('group_header', $content);
    field_group_fields_nest($header, $content);
    unset($content['#fieldgroups']['group_header']);
    unset($content['#groups']['group_header']);
    foreach ($header['#group_children'] as $c => $g) {
      unset($content[$c]);
      unset($content['#group_children'][$c]);
    }
    return $header;
  }
  return null;
}

function landportal_display_extract_groups($group_name, $content) {
  static $i = 0;
  $g = array(
    '#fieldgroups' => [],
    '#group_children' => [],
  );
  foreach ($content['#groups'][$group_name]->children as $field) {
    // Process nested groups
    if (substr($field, 0, 6) == 'group_') {
      $i++;
      $cg = landportal_display_extract_groups($field, $content);
      $i--;
      $g['#fieldgroups'][$field] = $cg['#fieldgroups'][$field];
      $g['#group_children'][$field] = $group_name;
      $g['#group_children'] += $cg['#group_children'];
      $g['#items'] += $cg['#items'];
      //unset($variables['page']['content']['system_main']['nodes'][$node->nid][$fieldc]);
    } else {
      if (isset($content[$field])) {
        $g['#items'][$field] = $content[$field];
        $g['#group_children'][$field] = $group_name;
      }
      //unset($variables['page']['content']['system_main']['nodes'][$node->nid][$field]);
    }
  }
  //dpm($g, 'E: '.$group_name);
  $g['#fieldgroups'][$group_name] = $content['#groups'][$group_name];
  $g += $g['#items'];
  if (!$i) unset($g['#items']);
  return $g;
}


/******************************************
 *
 *    Hacks for select2 on forms
 *
 * npm install select2
 *
 */

/* function landportal_display_theme_registry_alter(&$theme_registry) { */
/*   $theme_registry['select']['preprocess functions'][] = 'landportal_display_select'; */
/*   $theme_registry['select']['process functions'][] = 'landportal_display_select'; */
/*   dpm($theme_registry['select']); */
/* } */

/* function landportal_display_select(&$variables, $hook) { */
/*   landportal_display_add_select2($variables['element']); */
/*   $variables['element']['#attributes']['class'][] = 'STUFF'; */
/*   dpm($variables, $hook);//$variables['element']['#id']); */
/*   //return jump_menu_select($variables); */
/* } */

function landportal_display_add_select2(&$elem) {
  global $theme;
  if ($theme != 'lpbs') {
    $elem['#attached']['css'][] = drupal_get_path('module', 'landportal_display') . '/select2.css';
  }
  $elem['#attached']['js'][] = drupal_get_path('module', 'landportal_display') . '/select2.full.min.js';
  $elem['#attached']['js'][] = drupal_get_path('module', 'landportal_display') . '/select.js';
}

function landportal_display_form_alter(&$form, &$form_state, $form_id) {
  //dsm($form_id);
  $fields = array(
    // LL specific
    'field_doc_type',
    'field_doc_publisher',
    'field_doc_provider',
    // LB specific
    'field_indicators',
    'field_indicator_ranking',
    'field_indicator_map',
    /* // Admin views */
    'type', // CT type? // for view admin
    'field_doc_type_tid',
    'field_doc_publisher_tid',
    'field_doc_provider_tid',
    // Commons
    'field_featured',
    'field_orgref',
    'field_geographical_focus',
    'field_related_topics',
    'field_related_domains',
    'field_related_themes'
  );
  $select = array();
  // Quickly scan form for fields
  foreach($fields as $field) {
    if (array_key_exists($field, $form)) {
      $select[] = $field;
    }
  }

    // Do we have any matches (ie select field that uses jquery.select) ?
  $forms = array(
    'field_ui_field_overview_form', 'user_profile_form', 'user_register_form',
    'apachesolr_search_custom_page_search_form', 'views_exposed_form',
    'taxonomy-form-term', 'ctools_jump_menu'
  );
  if (count($select) || in_array($form_id, $forms) || preg_match('/^views_ui_/', $form_id)) {
    //dpm($select, 'selected fields');
    landportal_display_add_select2($form);
  }
}
