<?php
/**
 * @file
 * landlibrary_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function landlibrary_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-1Zglry1VFN0KlmWTGfpDnJ9c018MMCKS'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '1Zglry1VFN0KlmWTGfpDnJ9c018MMCKS',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'library/search*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'lpbs',
        'weight' => 17,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-Dz09BvvNFhfLdnmwFu0Zl165RuMvV0RW'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'Dz09BvvNFhfLdnmwFu0Zl165RuMvV0RW',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'lpbs',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-K6QeeeI0kUQwcRHw0ykqMagwrOG1BDbm'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'K6QeeeI0kUQwcRHw0ykqMagwrOG1BDbm',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'library/search*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'lpbs',
        'weight' => 13,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-On1jGuEOqF5IBeLzkIySMDCRhYYUP40E'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'On1jGuEOqF5IBeLzkIySMDCRhYYUP40E',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'library/search*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'lpbs',
        'weight' => 14,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-Q01KZ01pgIWhRBhu0uMVfwMYKhC5heYa'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'Q01KZ01pgIWhRBhu0uMVfwMYKhC5heYa',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'lpbs',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-SweA5o2kLHcd6EJKAdto5pVuxtYrdlAs'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'SweA5o2kLHcd6EJKAdto5pVuxtYrdlAs',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'library/search*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'lpbs',
        'weight' => 15,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-bNQti3i1QvYnpxR8B11gXwNRUVDR3Loz'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'bNQti3i1QvYnpxR8B11gXwNRUVDR3Loz',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'library/search*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'lpbs',
        'weight' => 12,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-ooMYLroTu5LFURMPW11d154eswrQld0K'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ooMYLroTu5LFURMPW11d154eswrQld0K',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'library/search*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'lpbs',
        'weight' => 18,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-xl143zAiuT3sYRQrYU4Ri6yOYzvDRMM5'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'xl143zAiuT3sYRQrYU4Ri6yOYzvDRMM5',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'library/search*',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'lpbs',
        'weight' => 16,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Filter by Issues',
    'visibility' => 1,
  );

  $export['facetapi-yUhemNJf8izLiuofmSC6AQ3PVGRxP5Hp'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'yUhemNJf8izLiuofmSC6AQ3PVGRxP5Hp',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'lpbs' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'lpbs',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
