<?php

function landbook_vis_map_theme($existing, $type, $theme, $path){
    return array(
        'region_map' => array('template' => 'block--landbook-vis-map--region-map'),
        'world_map'  => array('template' => 'block--landbook-vis-map--world-map'),
    );
}
function landbook_vis_map_library() {    
    $libraries['region-map'] = array(
        'title' => 'LBV region map', 
        'version' => '0.0.1',
        'js' => array(
            'js/region-mpa.js' => array(),
        ),
        'dependencies' => array(
            array('landbook', 'lbvis.map'),
        ),
    );
    return $libraries;
}

function landbook_vis_map_block_info() {
    $blocks['region_map'] = array(
        'info' => t('Landbook country Region map'),
        'status' => TRUE,
        'region' => 'content',
        'visibility'      => BLOCK_VISIBILITY_LISTED,
        'pages'           => "book/countries/*",
        'weight'      => -42
    );
    $blocks['world_map'] = array(
        'info' => t('Landbook country World map'),
        'status' => TRUE,
        'region' => 'content',
        'visibility'      => BLOCK_VISIBILITY_LISTED,
        'pages'           => "book/countries/*",
        'weight'      => 10
  );
  return $blocks;
}

function landbook_vis_map_block_view($delta = '') {
    //$library_path = libraries_get_path('lbvis');
    //$book_path   = drupal_get_path('module', 'landbook');
    $module_path = drupal_get_path('module', 'landbook_vis_map');

    $block = array();
    switch ($delta) {
    case 'region_map' :
        $lbl = drupal_get_library('landbook', 'lbvis.map');
        //dpm($lbl);
        $block['subject'] = '';
        $block['content'] = array(
            '#theme' => 'region_map',
            '#attached' => array(
                'library' => array(
                    array('landbook', 'lbvis.map'),
                ),
                'js' =>  array(
                    $module_path . '/region-map.js' =>  array('weight' => 3, 'requires_jquery' => TRUE),
                )
            )
        );
        break;
    case 'world_map' :
        $block['subject'] = 'Mapping';
        $block['content'] = array(
            '#theme' => 'world_map',
            '#attached' => array(
                'library' => array(
                    array('landbook', 'lbvis.map'),
                ),
                'js' =>  array(
                    $module_path . '/world-map.js' =>  array('weight' => 3, 'requires_jquery' => TRUE),
                )
            )
        );
        break;
    }
    return $block;
}
