<?php

function landbook_vis_map_block_info() {
  $blocks['region_map_block'] = array(
    'info' => t('Region Map Block'),
  );
  $blocks['world_map_block'] = array(
    'info' => t('World Map Block'),
  );

  return $blocks;
}

function landbook_vis_map_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'region_map_block' :
          $block['content'] = landbook_vis_map_region_map_block_view();
          break;
        case 'world_map_block' :
          $block['content'] = landbook_vis_map_world_map_block_view();
          break;
    }
    return $block;
}

function landbook_vis_map_region_map_block_view(){
  global $language;
  if(arg(0)=='book' && arg(1)=='countries' && !empty(arg(2))){
  $iso=arg(2);
  $r = new Country();
  $data = $r->get($language, $iso);
  return theme('region-map',array('data'=>$data));
  }
}
function landbook_vis_map_world_map_block_view(){
  $block = block_load('landbook_vis_map', 'world_map_block');
  return theme('world-map',array('title'=>$block->title));
}

function landbook_vis_map_theme($existing, $type, $theme, $path){
  return array(
    'region-map'  => array('template' => 'region-map','data' => NULL),
    'world-map'  => array('template' => 'world-map',array('title'=>NULL)),
  );
}

function landbook_vis_map_page_alter(&$page){
  $library_path = libraries_get_path('lbvis');
  drupal_add_js($library_path . '/js/lbvis.map.js');
  drupal_add_js(drupal_get_path('module', 'landbook_vis_map').'/main.js');
}