<?php
/**
 * @file
 * Code for the Landportal Geo feature.
 */

include_once 'landportal_geo.features.inc';

/**
 * Views hook
 */
function landportal_geo_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_views_default_views().
 * Automatically load all views found in MODULE/views/*.inc
 */
function landportal_geo_views_default_views() {
  $export = array();
  $path = drupal_get_path('module', 'landportal_geo').'/views';
  $files = file_scan_directory($path, '/\.inc$/');
  foreach ($files as $filepath => $file) {
    include_once $filepath;
    $export[$view->name] = $view;
  }
  return $export;
}


function landportal_geo_menu() {
  $items = array();
  // Provided by views/geo.inc
  $items['admin/content/landbook/countries'] = array(
    'title'             => 'Land Book Countries',
    'type'              => MENU_DEFAULT_LOCAL_TASK,
    'access arguments'  => array('administer taxonomy'),
    'callback'          => 'systems_view_data',
    'weight'            => 9,
  );
  return $items;
}

// Add country flag to iso3 field
function landportal_geo_field_attach_preprocess_alter(&$variables, $context) {
  if ($context['entity_type'] != 'taxonomy_term') return;
  $term = $context['entity'];
  if ($term->vocabulary_machine_name != 'regions') return;
  if (@$iso3 = $term->field_iso3[LANGUAGE_NONE][0]['value']) {
    $variables['content']['field_iso3'][0] = array(
      '#markup' => '<span class="iso3">'. $iso3 . '</span>',
      '#suffix' => '<span class="flag-icon flag-'. $iso3 . '"></span>'
    );
  }
}
