<?php



function landbook_country_page_image_default_styles() {
  $styles = array();

  // Exported image style: country_promoted.
  $styles['country_promoted'] = array(
    'label' => 'country promoted',
    'effects' => array(
      7 => array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 527,
          'height' => 260,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}

/* function landbook_country_page_HOOK() { */
/* } */

/**
 * Implements hook_custom_pub_defaults().
 */
function landbook_country_page_custom_pub_defaults() {
    $options = array();
    // Exported option: promoted_to_country_page
    $options['promoted_to_country_page'] = array(
        'type' => 'promoted_to_country_page',
        'name' => t('Promoted to country page'),
        'node_types' => array(
            'blog_post' => t('Blog post'),
            'debate' => t('Debate'),
            'event' => t('Event'),
            'landlibrary_resource' => t('LandLibrary Resource'),
            'news' => t('News'),
        ),
    );
    return $options;
}


  /* $strongarm = new stdClass(); */
  /* $strongarm->disabled = FALSE; /\* Edit this to true to make a default strongarm disabled initially *\/ */
  /* $strongarm->api_version = 1; */
  /* $strongarm->name = 'custom_pub_types'; */
  /* $strongarm->value = array( */
  /*   'promoted_to_country_page' => array( */
  /*     'type' => 'promoted_to_country_page', */
  /*     'name' => 'Promoted to country page', */
  /*     'default' => TRUE, */
  /*     'node_types' => array( */
  /*       'blog_post' => 'Blog post', */
  /*       'debate' => 'Debate', */
  /*       'event' => 'Event', */
  /*       'landlibrary_resource' => 'LandLibrary Resource', */
  /*       'news' => 'News', */
  /*     ), */
  /*   ), */
  /* ); */
  /* $export['custom_pub_types'] = $strongarm; */
