<?php
/**
 * @file
 * Code for the Landbook Country Page feature.
 */

function landbook_country_page_image_default_styles() {
  $styles = array();

  // Exported image style: country_promoted.
  $styles['country_promoted'] = array(
    'label' => 'country promoted',
    'effects' => array(
      7 => array(
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 527,
          'height' => 260,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}

/**
 * Implements hook_custom_pub_defaults().
 */
function landbook_country_page_custom_pub_defaults() {
    $options = array();
    // Exported option: promoted_to_country_page
    $options['promoted_to_country_page'] = array(
        'type' => 'promoted_to_country_page',
        'name' => t('Promoted to country page'),
        'node_types' => array(
            'blog_post' => t('Blog post'),
            'debate' => t('Debate'),
            'event' => t('Event'),
            'landlibrary_resource' => t('LandLibrary Resource'),
            'news' => t('News'),
        ),
    );
    return $options;
}
