<?php

/* Declare LGAF block */
function landbook_lgaf_block_info() {
  $blocks['vis'] = array(
    'info'      => t('View CODA: LGAF'),
    'status'    => TRUE,
    'region'    => 'content',
    'visibility'=> BLOCK_VISIBILITY_LISTED,
    'pages'     => "book/countries/*",
    'weight'    => -62,
  );
  return $blocks;
}

function landbook_lgaf_block_view($delta = '') {
  if ($delta != 'vis') return ;

  $PATH = libraries_get_path('js-view-coda');
  $jsAttr = 'jsonPath: "/' . $PATH . '/examples/json", iso3: Drupal.settings.landbook.countryCode';

  $block = array(
    'subject' => t('Land Governance Assessment Framework (LGAF)'),
    'content' => array(
      '#markup' => '<p>Note: Some Indicators might have multiple values (e.g. Green-Orange), which might refers to different localities or categories of people. For more information please refers to specific country reports and to the methodology made available by the original data source/provider: <a href="http://go.worldbank.org/21M7S7AZO0" target="_blank" class="ext">The Land GovernanceAssessment Framework (LGAF) website of the World Bank<span class="ext"><span class="element-invisible"> (link is external)</span></span></a></p>',
      '#attached' => array(
        'library' => array(
          array('landbook_view_coda', 'lbvis.lgaf')
        ),
        'js' => array(
          array(
            'type' => 'inline',
            'data' => lbvc__js_ready('LGAF = new lbvisLGAF(LBV, {'.$jsAttr.', target: "#block-landbook-lgaf-vis"}); LGAF.init();')
          )
        )
      )
    )
  );
  return $block;
}
