<?php
/**
 * @file
 * landlibrary_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function landlibrary_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Reports & Research',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '0e00119d-b478-4d58-bb38-355e5273da31',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3678,
          'revision_id' => 3678,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404156,
          'changed' => 1477404156,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'National Policies',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 3,
    'uuid' => '12f974ab-0144-47ab-b77a-e984eb4f000c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3992,
          'revision_id' => 3992,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404089,
          'changed' => 1477404089,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e85fa60b-91d0-49ea-8b44-f46bcc925dcf',
    ),
  );
  $terms[] = array(
    'name' => 'International Conventions or Treaties',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '14e2a781-b9d0-436b-be70-325f9aec7e53',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3991,
          'revision_id' => 3991,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404199,
          'changed' => 1477404199,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e85fa60b-91d0-49ea-8b44-f46bcc925dcf',
    ),
  );
  $terms[] = array(
    'name' => 'Constitution',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '5be0c818-ca86-4232-89fb-9f3b0b238d4a',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3659,
          'revision_id' => 3659,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404206,
          'changed' => 1477404206,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e85fa60b-91d0-49ea-8b44-f46bcc925dcf',
    ),
  );
  $terms[] = array(
    'name' => 'Policy Papers & Briefs',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => '6ec5c0b7-e3d4-4f45-9c90-df0da61c68ec',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3993,
          'revision_id' => 3993,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404186,
          'changed' => 1477404186,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Journal Articles & Books',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '795d74c2-9665-4a96-b246-a8ae0b058811',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3655,
          'revision_id' => 3655,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404136,
          'changed' => 1477404136,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Training Resources & Tools',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => '88d423e7-9956-4822-bd52-6ed84a1664b0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3987,
          'revision_id' => 3987,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404056,
          'changed' => 1477404056,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Peer-reviewed publication',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8915ee67-2edc-4f9a-9c0e-69a13684844e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3673,
          'revision_id' => 3673,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404150,
          'changed' => 1477404150,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '795d74c2-9665-4a96-b246-a8ae0b058811',
    ),
  );
  $terms[] = array(
    'name' => 'Manuals & Guidelines',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'c3a76572-fdef-47cf-913f-2216ecc10d63',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3663,
          'revision_id' => 3663,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477403902,
          'changed' => 1477403902,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'UN Resolutions',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => 'e00ce92f-dadc-4d8a-8a92-b8ba2ca92244',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3994,
          'revision_id' => 3994,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404078,
          'changed' => 1477404078,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e85fa60b-91d0-49ea-8b44-f46bcc925dcf',
    ),
  );
  $terms[] = array(
    'name' => 'Regulations',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => 'e14b20cf-5cba-4381-8cc4-abc5355582e8',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3677,
          'revision_id' => 3677,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404084,
          'changed' => 1477404084,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e85fa60b-91d0-49ea-8b44-f46bcc925dcf',
    ),
  );
  $terms[] = array(
    'name' => 'Legislation & Policies',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 5,
    'uuid' => 'e85fa60b-91d0-49ea-8b44-f46bcc925dcf',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3982,
          'revision_id' => 3982,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404192,
          'changed' => 1477404192,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Multimedia',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => 'f46e9a89-3241-4898-9354-6fb1af1098ad',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3671,
          'revision_id' => 3671,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404029,
          'changed' => 1477404029,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Legislation',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => 'f49e4f01-aaa0-4af0-ac92-2afe31de85f7',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'landlibrary_resource_type',
    'synonyms_synonyms' => array(),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 3668,
          'revision_id' => 3668,
          'language' => 'und',
          'source' => '',
          'uid' => 8157,
          'status' => 1,
          'translate' => 0,
          'created' => 1477404095,
          'changed' => 1477404095,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e85fa60b-91d0-49ea-8b44-f46bcc925dcf',
    ),
  );
  return $terms;
}
