<?php
/**
 * @file
 * landbook_promoted_thematic.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function landbook_promoted_thematic_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_thematic_promoted'.
  $field_bases['field_thematic_promoted'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_thematic_promoted',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 1,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'thematic_narrative' => 'thematic_narrative',
        ),
      ),
      'profile2_private' => FALSE,
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
