<?php
/**
 * @file
 * Code for the Landportal Blocks feature.
 */

include_once 'landportal_blocks.features.inc';
include_once 'landportal_blocks.blocks.inc';

/**
 * Implements hook_context_default_contexts().
 */
function landportal_blocks_context_default_contexts() {
  $export = array();

  // Import all files present in context directory
  $path = drupal_get_path('module', 'landportal_blocks').'/context';
  $files = file_scan_directory($path, '/\.inc$/');
  foreach ($files as $filepath => $file) {
    include_once $filepath;
    $export[$context->name] = $context;
  }
  return $export;
}


/**
 * Generate page internal navigation menu based on blocks ids and titles
 */
function landportal_blocks_page_submenu() {
  return 'var $ = jQuery.noConflict(); $(document).ready(function($) {
menu = $("#page-submenu .nav");
menu.empty();
  $(".region-content section.block").each(function (i, e) {
  title = $(e).find("h2.block-title")[0];
if (!title || !title.innerHTML || title.innerHTML == "<none></none>" || title.innerHTML.startsWith("Latest ")) return;
//console.log(e.id, title.innerHTML);
menu.append("<li><a href=\"#" + e.id + "\">" + title.innerHTML + "</li>");
});
});';
}
