<?php
/**
 * @file
 * Code for the Landportal Blocks feature.
 */

include_once 'landportal_blocks.features.inc';
include_once 'landportal_blocks.blocks.inc';

/**
 * Implements hook_context_default_contexts().
 */
function landportal_blocks_context_default_contexts() {
  $export = array();

  // Import all files present in context directory
  $path = drupal_get_path('module', 'landportal_blocks').'/context';
  $files = file_scan_directory($path, '/\.inc$/');
  foreach ($files as $filepath => $file) {
    $context = NULL;
    include_once $filepath;
    if ($context) {
      $export[$context->name] = $context;
    }
  }
  return $export;
}


/**
 * Generate page internal navigation menu based on blocks ids and titles
 */
function landportal_blocks_page_submenu() {
  return file_get_contents(drupal_get_path('module', 'landportal_blocks') . '/landportal_blocks.js');
}
