<?php
/*
 * This module provides various elements for the Landportal taxonomies 
 */

include_once 'landportal_taxonomy.features.inc';

/**
 * Implements hook_views_api().
 */
function landportal_taxonomy_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/* function landportal_taxonomy_block_info_alter(&$blocks, $theme, $code_blocks) { */
/*     if ($theme == 'landportal') { */
/*         $blocks['views']['domains-block'] = array_merge( */
/*             $blocks['views']['domains-block'], */
/*             array( */
/*                 'info' => t('Landvoc Overarching categories'), */
/*                 'region' => 'content', */
/*                 'status' => TRUE, */
/*                 'weight' => 10, */
/*                 'visibility' => BLOCK_VISIBILITY_LISTED, */
/*                 'pages' => 'voc/landvoc' */
/*             ) */
/*         ); */
/*         $blocks['views']['themes-block'] = array_merge( */
/*             $blocks['views']['themes-block'], array( */
/*                 'info' => t('Landvoc Themes'), */
/*                 'region' => 'content', */
/*                 'status' => TRUE, */
/*                 'weight' => 11, */
/*                 'visibility' => BLOCK_VISIBILITY_LISTED, */
/*                 'pages' => 'voc/landvoc' */
/*             ) */
/*         ); */
/*         $blocks['views']['concepts-block'] = array_merge( */
/*             $blocks['views']['concepts-block'], array( */
/*                 'info' => t('Landvoc Concepts'), */
/*                 'region' => 'content', */
/*                 'status' => TRUE, */
/*                 'weight' => 12, */
/*                 'visibility' => BLOCK_VISIBILITY_LISTED, */
/*                 'pages' => 'voc/landvoc' */
/*             ) */
/*         ); */
/*         return $blocks; */
/*     } */
/* } */
