<?php
/**
 * @file
 * Code for the Landportal Drupal Profiles
 *

For, profile without use accounts, see:
https://www.drupal.org/node/1612578
profile2_create
https://www.drupal.org/sandbox/guillaumev/2039905
git clone git://git.drupal.org/sandbox/guillaumev/2039905.git profile2_create

 */

/* function landportal_profiles_user($op, &$edit, &$account, $category = NULL) { */
/*   dsm('HOOK ' . $op); */
/*   dpm($account, 'account'); */
/*   dpm($edit, 'edit'); */
/* } */

function landportal_profiles_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    global $user;
    
    /* dpm($form, $form_id); */
    /* dpm($user, 'user'); */
    // Move account roles field to group admin
    /* $form['roles'] = $form['account']['roles']; */
    /* unset($form['account']['roles']); */
    /* $form['#groups']['group_admin']->children[] = 'roles'; */
    //$form['#groups']['group_admin']->children[] = $form['account']['status'];
    //$form['#groups']['group_settings']->children[] = 'location';
  }
}
function landportal_profiles_admin_paths_alter(&$paths) {
  //dsm('removed from admin');
    // Treat all user pages as not administrative.
    $paths['user/*'] = FALSE;
}
