<?php
use mikehaertl\wkhtmlto\Pdf;

function landportal_pdf_preprocess_page(&$variables){
    
  if (arg(0) == 'book' && arg(1) == 'countries' && arg(3) == 'pdf' ) {
      $url = 'http'.(@$_SERVER['HTTPS'] ? 's' : '').'://'.$_SERVER['HTTP_HOST'].'/'.str_replace('/pdf','',current_path());
      landportal_pdf_generate_pdf($url,arg(2));
  }
  if(arg(0)=='node' && arg(2) == 'pdf'){
      $node=node_load(arg(1));
      if($node->type=='thematic_narrative'){
          $url='http'.(@$_SERVER['HTTPS'] ? 's' : '').'://'.$_SERVER['HTTP_HOST'].'/'.drupal_get_path_alias('node/' . $node->nid);
          landportal_pdf_generate_pdf($url,$node->title);
      }
  }

  $image = landportal_pdf_get_narrative();
  $variables['print_logo_image'] = '';
  if(!empty($image)){
     $variables['print_logo_image']='<div class="print-organization"><p>'.t('Country page powered by').'</p>'.$image.'</div>';
  }
}

function landportal_pdf_get_narrative(){
  $args = arg();
  if ($args[0] == 'book' && $args[1] == 'countries' && isset($args[2])) {
    global $language;
    $tid = landbook_get_region_iso($args[2]);
    $term = taxonomy_term_load($tid);
    $node_id = landportal_pdf_get_country_narrative_nid($term->name);
    $image = '';
    if(!empty($node_id)){
      $node = node_load($node_id);
      $items = field_get_items('node', $node, 'field_orgref');
      if(!empty($items)){
        $item = array_shift($items);
        if(isset($item['entity'])){
          $items = field_get_items('node', $item['entity'], 'field_image');
          $url = $items[0]['uri'];
          $params = array(
            'style_name' => 'medium',
            'path' => $url,
          );
          $image = theme('image_style', $params);
        }
        else{
          $image = '';
        }
      }
    }
    return $image;
  }
}

function landportal_pdf_get_country_narrative_nid($title){
  $nid = db_select('node', 'n')
  ->fields('n', array('nid'))
  ->condition('n.title', $title)
  ->condition('n.type', 'landbook_country')
  ->execute()
  ->fetchField();
  return $nid;
}


function landportal_pdf_generate_pdf($url,$name){
    if (($library = libraries_load('phpwkhtmltopdf')) && !empty($library['loaded'])) {
        drupal_add_css(path_to_theme() . '/css/printpdf.css', array('group' => CSS_THEME, 'weight' => 115, 'preprocess' => TRUE,'media'=>'print'));
        $pdf = new Pdf();
        $pdf->binary = '/usr/bin/xvfb-run -- /usr/local/bin/wkhtmltopdf';
        $pdf->setOptions(array(
          'page-size'=>'A4',
          'javascript-delay' => 1000,
          'margin-top'=>10,
          'margin-left'=>0,
          'margin-right'=>0,
          'margin-bottom'=>'1cm',
          'user-style-sheet'=>drupal_get_path('module', 'landportal_pdf') . '/printpdf.css' ,
        ));
        //$url = 'http://'.$_SERVER['HTTP_HOST'].'/'.str_replace('/pdf','',current_path());
        $pageOptions = array(
          'enable-javascript',
          'no-stop-slow-scripts',
          'debug-javascript',
          'print-media-type'
          );
         $pdf->addPage($url,$pageOptions);
         $pdf->send($name.'.pdf');
         if ($error = $pdf->getError()) {
           watchdog('landportal_pdf', 'PDF generation error', array($error), WATCHDOG_ERROR);
         }
    }
}