<?php
/**
 * The Land Portal
 *
 * Project: Land Book
 * Mdule: landbook_admin
 *
 * Author: Jules C. <jules@ker.bz>
 *
 * @file
 * This module provide an administrative interface to the Land Book
 *
 */

/**
 * Load views API
 */
function landbook_admin_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_views_default_views().
 */
function landbook_admin_views_default_views() {
    $export = array();

    $path = drupal_get_path('module', 'landbook_admin').'/views';
    $files = file_scan_directory($path, '/\.inc$/');
    foreach ($files as $filepath => $file) {
      include_once $filepath;
      $export[$view->name] = $view;
    }
    return $export;
}

function landportal_admin_help($path, $arg) {
  switch ($path) {
  case "admin/help#landbook_admin":
    return '<p>' . t("Land Book Administration, what else?") . '</p>';
    break;
  }
}

function landbook_admin_menu() {
  $items = array();

  // LB content management
  /* $items['admin/content/landbook'] = array( */
  /*   'title'             => 'Land Book', */
  /*   'description'       => 'Land Book content (Catalogs, Datasets, Indicators...)', */
  /*   'postition'         => 'right', */
  /*   'weight'            => -4, */
  /*   'page callback'     => 'system_admin_menu_block_page', */
  /*   'access arguments'  => array('edit any dataset content'), // Should be admin 'edit terms in' datasets, indicators */
  /*   'file'              => 'system.admin.inc', */
  /*   'file path'         => drupal_get_path('module', 'system'), */
  /* ); */
  // Provided by views/lbadm_catalogs.inc
  $items['admin/content/landbook'] = array(
    'title'             => 'Land Book',
    //'type'              => MENU_DEFAULT_LOCAL_TASK,
    'access arguments'  => array('edit terms in 24'), // 24 = datasets
    'callback'          => 'systems_view_data',
  );

  // Provided by views/lbadm_indicators.inc
  $items['admin/content/landbook/ds/%taxonomy_term'] = array(
    'title'             => '',
    'type'              => MENU_LOCAL_TASK,
    'access arguments'  => array('edit terms in 25'), // 25 = indicators
    'callback'          => 'systems_view_data',
    'page arguments' => array(2),
    'weight'            => 11,
  );
  return $items;
}

function landbook_admin_add_ind($cid, $args) {
  drupal_set_title('Land Book add indicator');
  dpm($args, 'lb add ind ', $cid);
  return ;
}
