<?php
/**
 * The Land Portal
 *
 * Project: Land Book
 * Mdule: landbook_admin
 *
 * Author: Jules C. <jules@ker.bz>
 *
 * @file
 * This module provide an administrative interface to the Land Book
 *
 */

/**
 * Load views API
 */
function landbook_admin_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_views_default_views().
 */
function landbook_admin_views_default_views() {
    $export = array();

    $path = drupal_get_path('module', 'landbook_admin').'/views';
    $files = file_scan_directory($path, '/\.inc$/');
    foreach ($files as $filepath => $file) {
      include_once $filepath;
      $export[$view->name] = $view;
    }
    return $export;
}

function landportal_admin_help($path, $arg) {
  switch ($path) {
  case "admin/help#landbook_admin":
    return '<p>' . t("Land Book Administration, what else?") . '</p>';
    break;
  }
}

function landbook_admin_menu() {
  $items = array();

  // Provided by views/lbadm_catalogs.inc
  $items['admin/content/landbook'] = array(
    'title'             => 'Land Book',
    'type'              => MENU_NORMAL_ITEM,
    'access arguments'  => array('edit terms in 24'), // 24 = datasets
    'page callback' => 'views_embed_view',
    'page arguments' => array('lbadm_catalogs', 'system'),
    'file path' => drupal_get_path('module', 'views'),
    'file'      => 'views.module',
  );

  $items['admin/content/landbook/datasets'] = array(
    'title'             => 'Datasets',
    'type'              => MENU_LOCAL_TASK,
    'access arguments'  => array('edit terms in 24'), // 24 = datasets
    'weight'            => 9,
  );

  $items['admin/content/landbook/indicators'] = array(
    'title'             => 'Indicators',
    'type'              => MENU_LOCAL_TASK,
    'access arguments'  => array('edit terms in 25'), // 25 = indicators
    'weight'            => 10,
  );

  // Provided by views/lbadm_indicators.inc
  $items['admin/content/landbook/datasets/%taxonomy_term'] = array(
    'title'             => 'I in D',
    'type'              => MENU_CALLBACK,
    'access arguments'  => array('edit terms in 25'), // 25 = indicators
    'page arguments' => array(2),
  );
  return $items;
}
