<?php
/**
 * The Land Portal
 *
 * Project: Land Book
 * Mdule: landbook_admin
 *
 * Author: Jules C. <jules@ker.bz>
 *
 * @file
 * This module provide an administrative interface to the Land Book
 *
 */

/**
 * Load views API
 */
function landbook_admin_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_views_default_views().
 */
function landbook_admin_views_default_views() {
    $export = array();

    $path = drupal_get_path('module', 'landbook_admin').'/views';
    $files = file_scan_directory($path, '/\.inc$/');
    foreach ($files as $filepath => $file) {
      include_once $filepath;
      $export[$view->name] = $view;
    }
    return $export;
}

function landportal_admin_help($path, $arg) {
  switch ($path) {
  case "admin/help#landbook_admin":
    return '<p>' . t("Land Book Administration, what else?") . '</p>';
    break;
  }
}

function landbook_admin_menu() {
  $items = array();
  // LB module configuration (original / to be updated with useful, internal, LB module settings)
  $items['admin/config/landbook'] = array(
    'title'             => 'Landbook',
    'description'       => 'Configure the landbook',
    'postition'         => 'right',
    'weight'            => -4,
    'page callback'   	=> 'system_admin_menu_block_page',
    'access arguments'  => array('administer site configuration'),
    'file'              => 'system.admin.inc',
    'file path'         => drupal_get_path('module', 'system'),
  );
  $items['admin/config/landbook/settings'] = array(
    'title'             => 'Landbook settings',
    'description'       => 'Base landbook configuration',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('landbook_admin_settings'),
    'access arguments'  => array('administer site configuration'),
    'file'              => 'landbook_admin.admin.inc',
    'file path'         => drupal_get_path('module', 'landbook_admin'),
  );

  // LB content management
  $items['admin/content/landbook'] = array(
    'title'             => 'Land Book',
    'description'       => 'Land Book content (Catalogs, Datasets, Indicators...)',
    'postition'         => 'right',
    'weight'            => -4,
    'page callback'     => 'system_admin_menu_block_page',
    'access arguments'  => array('administer taxonomy'), // Should be admin 'edit terms in' datasets, indicators
    'file'              => 'system.admin.inc',
    'file path'         => drupal_get_path('module', 'system'),
  );
  // Provided by views/lbadm_catalogs.inc
  /* $items['admin/content/landbook/catalogs'] = array( */
  /*   'title'             => 'Catalogs', */
  /*   'type'              => MENU_CALLBACK, */
  /*   'access arguments'  => array('administer taxonomy'), */
  /*   'callback'          => 'systems_view_data', */
  /*   'weight'            => 10, */
  /* ); */
  $items['admin/content/landbook/catalog/%'] = array(
    'title'             => 'Catalogs indicators',
    'type'              => MENU_LOCAL_ACTION,
    'access arguments'  => array('administer taxonomy'),
    'callback'          => 'systems_view_data',
    'weight'            => 11,
  );
  // Provided by views/lbadm_indicators.inc
  /* $items['admin/content/landbook/indicators'] = array( */
  /*   'title'             => 'Indicators', */
  /*   'type'              => MENU_CALLBACK, */
  /*   'access arguments'  => array('administer taxonomy'), */
  /*   'callback'          => 'systems_view_data', */
  /*   'weight'            => 10, */
  /* ); */
  return $items;
}
