<?php
/**
 * @file
 * Code for the Mailchimp Feature feature.
 */

include_once 'mailchimp_feature.features.inc';

/**
 * Stuff from landportal_utility
 * Webcoding studio never bothered to explain those hooks.
 * It seems like most of this can be done better by the MC module...
 */
function mailchimp_feature_form_user_register_form_alter(&$form, &$form_state,$form_id){
  $form['mailchimp_lists']['#collapsible'] = TRUE;
  $form['mailchimp_lists']['#collapsed'] = FALSE;
  $form['mailchimp_lists']['mailchimp_land_portal_news_digest']['interest_groups'][1]['#default_value']=array('English' => 'English');
  $form['#validate'][]='mailchimp_feature_validate_mailchimp_lists_user_subscribe';
  $form['#submit'][]='mailchimp_feature_mailchimp_user_update';
}

// Check that the user chose at least one language?
function mailchimp_feature_validate_mailchimp_lists_user_subscribe($form, &$form_state){
  if($form_state['values']['mailchimp_lists']['mailchimp_land_portal_news_digest']['subscribe'] == 1){
    $languages=$form_state['values']['mailchimp_lists']['mailchimp_land_portal_news_digest']['interest_groups'][1];
    $flag = false;
    foreach($languages as $lang){
      if($lang !== 0){
        $flag = TRUE;
      }
    }
    if($flag == false){
      form_set_error('', 'Please select language');
    }
  }
}
// This will not work anymore with new API...
function mailchimp_feature_mailchimp_user_update($form, &$form_state){
  if(isset($form_state['values']['account'])){
    $account=$form_state['values']['account'];
  }
  if(isset($form_state['values']['uid'])){
    $account=user_load($form_state['values']['uid']);
  }
  $lists = mailchimp_lists_get_available_lists($account);
  $mcapi = mailchimp_get_api_object();

  foreach ($lists as $list_key=>$list){
    if($list->name == 'land_portal_news_digest'){
    $mergevars = _mailchimp_lists_build_update_mergevars($account, $list, $account->mail, $account->mail);
    $profile=profile2_by_uid_load($account->uid, 'main');
    $fname=field_get_items('profile2', $profile, 'field_firstname');
    $lname=field_get_items('profile2', $profile, 'field_lastname');
    $mergevars['FNAME']=$fname[0]['value'];
    $mergevars['LNAME']=$lname[0]['value'];
    mailchimp_lists_execute_change('update', $list, $account->mail, $mergevars, NULL, $mcapi);
    }
  }
}
