<?php
/**
 * @file
 * Code for MOD projects importer using CSV.
 */

include_once('mod_projects_csv_importer.feeds_importer.inc');
include_once('mod_projects_csv_importer.feeds_tamper.inc');

function mod_projects_csv_importer_ctools_plugin_api($module = '', $api = '') {
    if ($module == "feeds_tamper" && $api == "feeds_tamper_default") {
        return array("version" => "2");
    }
    if ($module == "feeds" && $api == "feeds_importer_default") {
        return array("version" => "1");
    }
}
