<?php
/**
 * @file
 * Code for ODM library importer / using CKAN JSON.
 */

include_once('odm_library_importer.feeds_importer.inc');
include_once('odm_library_importer.feeds_tamper.inc');

function odm_library_importer_ctools_plugin_api($module = '', $api = '') {
    if ($module == "feeds_tamper" && $api == "feeds_tamper_default") {
        return array("version" => "2");
    }
    if ($module == "feeds" && $api == "feeds_importer_default") {
        return array("version" => "1");
    }
}
