<?php
/**
 * @file
 * landbook_taxonomies.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function landbook_taxonomies_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
  if ($module == "taxonomy_display" && $api == "taxonomy_display") {
    return array("version" => "1");
  }
}
