<?php
/**
 * @file
 * landbook_taxonomies.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function landbook_taxonomies_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'taxonomy_term-datasets-description_field'.
  $field_instances['taxonomy_term-datasets-description_field'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 10,
      ),
      'search_index' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'description_field',
    'label' => 'Catalog description',
    'required' => 0,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'filtered_html' => array(
              'weight' => -9,
            ),
            'full_html' => array(
              'weight' => -10,
            ),
            'plain_text' => array(
              'weight' => -8,
            ),
          ),
        ),
      ),
      'display_summary' => 0,
      'entity_translation_sync' => FALSE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_id'.
  $field_instances['taxonomy_term-datasets-field_id'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'full' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
      'search_index' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_id',
    'label' => 'ID',
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'filtered_html' => array(
              'weight' => -10,
            ),
            'full_html' => array(
              'weight' => -9,
            ),
            'plain_text' => array(
              'weight' => -8,
            ),
          ),
        ),
      ),
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_orgref'.
  $field_instances['taxonomy_term-datasets-field_orgref'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => 1,
          'view_mode' => 'teaser',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 5,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => TRUE,
          'view_mode' => 'teaser',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 6,
      ),
      'search_index' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'bypass_access' => FALSE,
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'bypass_access' => 0,
          'link' => 1,
        ),
        'type' => 'entityreference_label',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'entityconnect' => array(
      'button' => array(
        'unload_add_button' => 1,
        'unload_edit_button' => 1,
      ),
      'icon' => array(
        'show_add_icon' => 0,
        'show_edit_icon' => 0,
      ),
    ),
    'entityconnect_show_add_icon' => 0,
    'entityconnect_show_edit_icon' => 0,
    'entityconnect_unload_add' => 1,
    'entityconnect_unload_edit' => 1,
    'field_name' => 'field_orgref',
    'label' => 'Organization',
    'required' => 1,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'apply_chosen' => '',
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'options_select',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_related_aside'.
  $field_instances['taxonomy_term-datasets-field_related_aside'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 10,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_aside',
    'label' => 'Related aside',
    'required' => 0,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'apachesolr_search' => 0,
        'block' => 'block',
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'devel' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 0,
        'landbook_vggt' => 0,
        'landbook_view_coda' => 'landbook_view_coda',
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_related_blocks'.
  $field_instances['taxonomy_term-datasets-field_related_blocks'] = array(
    'bundle' => 'datasets',
    'default_value' => array(
      0 => array(
        'moddelta' => 'views:lbcat-block',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 10,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_blocks',
    'label' => 'Related blocks',
    'required' => 0,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'apachesolr_search' => 0,
        'block' => 0,
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'devel' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 0,
        'landbook_vggt' => 0,
        'landbook_view_coda' => 0,
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_related_domains'.
  $field_instances['taxonomy_term-datasets-field_related_domains'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 3,
      ),
      'search_index' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'links' => TRUE,
          'use_content_language' => TRUE,
          'view_mode' => 'default',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 12,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_domains',
    'label' => 'Overarching categories',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'synonyms',
      'settings' => array(
        'auto_creation' => 1,
        'size' => 60,
        'sort' => 'weight',
        'suggest_only_unique' => 0,
        'suggestion_size' => 10,
        'synonyms_autocomplete_path' => 'synonyms/autocomplete',
      ),
      'type' => 'synonyms_select_taxonomy_term',
      'weight' => 109,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_related_themes'.
  $field_instances['taxonomy_term-datasets-field_related_themes'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 4,
      ),
      'search_index' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'links' => TRUE,
          'use_content_language' => TRUE,
          'view_mode' => 'default',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 13,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_themes',
    'label' => 'Themes',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'synonyms',
      'settings' => array(
        'sort' => 'weight',
      ),
      'type' => 'synonyms_select_taxonomy_term',
      'weight' => 110,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_related_topics'.
  $field_instances['taxonomy_term-datasets-field_related_topics'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter a Topics term to classify your content. Those terms are in direct correlation with Agrovoc.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 5,
      ),
      'search_index' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'links' => TRUE,
          'use_content_language' => TRUE,
          'view_mode' => 'default',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 14,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_topics',
    'label' => 'Related concepts',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'synonyms',
      'settings' => array(
        'sort' => 'weight',
      ),
      'type' => 'synonyms_select_taxonomy_term',
      'weight' => 111,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_view_dataset'.
  $field_instances['taxonomy_term-datasets-field_view_dataset'] = array(
    'bundle' => 'datasets',
    'default_value' => array(
      0 => array(
        'moddelta' => 'views:landbook_catalog-dataset',
      ),
    ),
    'deleted' => 0,
    'description' => 'Display this catalog\'s datasets',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'full' => array(
        'label' => 'above',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 9,
      ),
      'search_index' => array(
        'label' => 'above',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_view_dataset',
    'label' => 'Published dataset(s)',
    'required' => 0,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'block' => 0,
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'devel' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 0,
        'landbook' => 0,
        'landbook_vggt' => 0,
        'landbook_view_coda' => 0,
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_view_indicators'.
  $field_instances['taxonomy_term-datasets-field_view_indicators'] = array(
    'bundle' => 'datasets',
    'default_value' => array(
      0 => array(
        'moddelta' => 'views:lbcat-jump',
      ),
    ),
    'deleted' => 0,
    'description' => 'Show indicators within the same catalog',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 7,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_view_indicators',
    'label' => 'view_indicators',
    'required' => 0,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'apachesolr_search' => 0,
        'block' => 0,
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'devel' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 0,
        'landbook_vggt' => 0,
        'landbook_view_coda' => 0,
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_view_latest'.
  $field_instances['taxonomy_term-datasets-field_view_latest'] = array(
    'bundle' => 'datasets',
    'default_value' => array(
      0 => array(
        'moddelta' => 'views:landbook_catalog-ds_latest',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 8,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 5,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_view_latest',
    'label' => 'Latest dataset',
    'required' => 0,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'apachesolr_search' => 0,
        'block' => 0,
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 0,
        'landbook' => 0,
        'landbook_vggt' => 0,
        'landbook_view_coda' => 0,
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-field_visualization'.
  $field_instances['taxonomy_term-datasets-field_visualization'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'landbook_view_coda',
        'settings' => array(
          'class' => '',
          'view_mode' => 'full',
        ),
        'type' => 'lbvc_block',
        'weight' => 9,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_visualization',
    'label' => 'Land Book Indicators',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'field_collection',
      'settings' => array(),
      'type' => 'field_collection_embed',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'taxonomy_term-datasets-name_field'.
  $field_instances['taxonomy_term-datasets-name_field'] = array(
    'bundle' => 'datasets',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => 'content',
          'title_style' => 'h2',
        ),
        'type' => 'title_linked',
        'weight' => 0,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => '',
          'title_style' => 'h1',
        ),
        'type' => 'title_linked',
        'weight' => 0,
      ),
      'search_index' => array(
        'label' => 'above',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => '',
          'title_style' => '',
        ),
        'type' => 'title_linked',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => 'content',
          'title_style' => 'h3',
        ),
        'type' => 'title_linked',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'name_field',
    'label' => 'Name',
    'required' => TRUE,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'hide_label' => array(
        'entity' => FALSE,
        'page' => FALSE,
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-description_field'.
  $field_instances['taxonomy_term-indicators-description_field'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 30,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 200,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'description_field',
    'label' => 'Indicator description',
    'required' => 0,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'filtered_html' => array(
              'weight' => -9,
            ),
            'full_html' => array(
              'weight' => -10,
            ),
            'plain_text' => array(
              'weight' => -8,
            ),
          ),
        ),
      ),
      'display_summary' => 0,
      'entity_translation_sync' => FALSE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_dataset'.
  $field_instances['taxonomy_term-indicators-field_dataset'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'The catalog this indicators it belongs to',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => 1,
          'view_mode' => 'default',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 1,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => 1,
          'view_mode' => 'default',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 1,
      ),
      'search_index' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 15,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_dataset',
    'label' => 'Catalog',
    'required' => 1,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'synonyms',
      'settings' => array(
        'sort' => 'weight',
      ),
      'type' => 'synonyms_select_taxonomy_term',
      'weight' => 0,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_hascodedvalue'.
  $field_instances['taxonomy_term-indicators-field_hascodedvalue'] = array(
    'bundle' => 'indicators',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'The values for this indicator is taken from some controlled term list (could be characters, colors, strings, numbers...)
<a href="https://www.w3.org/TR/vocab-data-cube/#schemes">Read more</a>',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 8,
      ),
      'full' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 8,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 17,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_hascodedvalue',
    'label' => 'has Coded Value',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_highlow'.
  $field_instances['taxonomy_term-indicators-field_highlow'] = array(
    'bundle' => 'indicators',
    'default_value' => array(
      0 => array(
        'value' => 1,
      ),
    ),
    'deleted' => 0,
    'description' => 'High means it is better to have a high value, low means the best value is the lowest one (like in rankings)',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 30,
      ),
      'full' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 10,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 11,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 16,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_highlow',
    'label' => 'Best value is',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_id'.
  $field_instances['taxonomy_term-indicators-field_id'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => '',
          'title_style' => '',
        ),
        'type' => 'title_linked',
        'weight' => 27,
      ),
      'full' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 7,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_id',
    'label' => 'ID',
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'filtered_html' => array(
              'weight' => -10,
            ),
            'full_html' => array(
              'weight' => -9,
            ),
            'plain_text' => array(
              'weight' => -8,
            ),
          ),
        ),
      ),
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_max'.
  $field_instances['taxonomy_term-indicators-field_max'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Maximun possible value of the indicator',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'full' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 10,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 14,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_max',
    'label' => 'max',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_min'.
  $field_instances['taxonomy_term-indicators-field_min'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Minimun possible value of the indicator',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'full' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 9,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'inline',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 15,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_min',
    'label' => 'min',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_observations'.
  $field_instances['taxonomy_term-indicators-field_observations'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 1,
          'use_content_language' => 1,
          'view_mode' => 'teaser',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 31,
      ),
      'full' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => 1,
          'view_mode' => 'teaser',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 11,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 9,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_observations',
    'label' => 'Observations',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 116,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_related_aside'.
  $field_instances['taxonomy_term-indicators-field_related_aside'] = array(
    'bundle' => 'indicators',
    'default_value' => array(
      0 => array(
        'moddelta' => 'landbook_view_coda:indicator_dl',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 32,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 12,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_aside',
    'label' => 'Related aside',
    'required' => 0,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'apachesolr_search' => 0,
        'block' => 'block',
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'devel' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 'jump_menu',
        'landbook_vggt' => 0,
        'landbook_view_coda' => 'landbook_view_coda',
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 118,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_related_blocks'.
  $field_instances['taxonomy_term-indicators-field_related_blocks'] = array(
    'bundle' => 'indicators',
    'default_value' => array(
      0 => array(
        'moddelta' => 'views:lbind-childs',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 31,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 5,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 10,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_blocks',
    'label' => 'Related blocks',
    'required' => 0,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'apachesolr_search' => 0,
        'block' => 'block',
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'devel' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 0,
        'landbook_vggt' => 0,
        'landbook_view_coda' => 0,
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 117,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_related_domains'.
  $field_instances['taxonomy_term-indicators-field_related_domains'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 26,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 10,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 16,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_domains',
    'label' => 'Overarching categories',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'synonyms',
      'settings' => array(
        'auto_creation' => 1,
        'size' => 60,
        'sort' => 'weight',
        'suggest_only_unique' => 0,
        'suggestion_size' => 10,
        'synonyms_autocomplete_path' => 'synonyms/autocomplete',
      ),
      'type' => 'synonyms_select_taxonomy_term',
      'weight' => 109,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_related_themes'.
  $field_instances['taxonomy_term-indicators-field_related_themes'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 27,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 11,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 17,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_themes',
    'label' => 'Themes',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'synonyms',
      'settings' => array(
        'sort' => 'weight',
      ),
      'type' => 'synonyms_select_taxonomy_term',
      'weight' => 110,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_related_topics'.
  $field_instances['taxonomy_term-indicators-field_related_topics'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter a Topics term to classify your content. Those terms are in direct correlation with Agrovoc.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 28,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 12,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 18,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_related_topics',
    'label' => 'Related concepts',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'synonyms',
      'settings' => array(
        'sort' => 'weight',
      ),
      'type' => 'synonyms_select_taxonomy_term',
      'weight' => 111,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_unit'.
  $field_instances['taxonomy_term-indicators-field_unit'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Measurement unit, like % or hectares',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 29,
      ),
      'full' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'inline',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => '',
          'title_style' => '',
        ),
        'type' => 'title_linked',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_unit',
    'label' => 'Measurement unit',
    'required' => 0,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'filtered_html' => array(
              'weight' => -10,
            ),
            'full_html' => array(
              'weight' => -9,
            ),
            'plain_text' => array(
              'weight' => -8,
            ),
          ),
        ),
      ),
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_view_indicators'.
  $field_instances['taxonomy_term-indicators-field_view_indicators'] = array(
    'bundle' => 'indicators',
    'default_value' => array(
      0 => array(
        'moddelta' => 'views:lbind-jump',
      ),
    ),
    'deleted' => 0,
    'description' => 'Show indicators within the same catalog',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 26,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 6,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 8,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_view_indicators',
    'label' => 'Indicators menu',
    'required' => 1,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'apachesolr_search' => 0,
        'block' => 0,
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'devel' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 0,
        'landbook_vggt' => 0,
        'landbook_view_coda' => 0,
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 114,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_view_parent'.
  $field_instances['taxonomy_term-indicators-field_view_parent'] = array(
    'bundle' => 'indicators',
    'default_value' => array(
      0 => array(
        'moddelta' => 'views:lbind-parent',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 2,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'blockreference',
        'settings' => array(
          'show_empty_blocks' => FALSE,
        ),
        'type' => 'blockreference_default',
        'weight' => 2,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_view_parent',
    'label' => 'View parent',
    'required' => 0,
    'settings' => array(
      'blockreference_modules' => array(
        'addtoany' => 0,
        'apachesolr_search' => 0,
        'block' => 0,
        'calendar' => 0,
        'comment' => 0,
        'context_ui' => 0,
        'devel' => 0,
        'diff' => 0,
        'facetapi' => 0,
        'global_filter' => 0,
        'hybridauth' => 0,
        'jump_menu' => 0,
        'landbook_vggt' => 0,
        'landbook_view_coda' => 0,
        'landbook_vis_map' => 0,
        'landbook_vis_table_indicators' => 0,
        'landportal_blocks' => 0,
        'landportal_partners' => 0,
        'locale' => 0,
        'login_one_time' => 0,
        'logintoboggan' => 0,
        'mailchimp_signup' => 0,
        'masquerade' => 0,
        'menu' => 0,
        'node' => 0,
        'og_menu' => 0,
        'pcp' => 0,
        'print' => 0,
        'search' => 0,
        'shortcut' => 0,
        'system' => 0,
        'twitter_block' => 0,
        'user' => 0,
        'views' => 'views',
        'webform' => 0,
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 115,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-field_visualization'.
  $field_instances['taxonomy_term-indicators-field_visualization'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'field_collection',
        'settings' => array(
          'add' => '',
          'delete' => '',
          'description' => 0,
          'edit' => '',
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_view',
        'weight' => 7,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 11,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_visualization',
    'label' => 'Land Book Indicators',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'field_collection',
      'settings' => array(
        'collapsed' => 1,
        'field_as_label' => 'title_field',
        'last_item_collapsed' => 1,
        'new_item_open' => 1,
        'replace_label' => 0,
      ),
      'type' => 'field_collection_embed',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'taxonomy_term-indicators-name_field'.
  $field_instances['taxonomy_term-indicators-name_field'] = array(
    'bundle' => 'indicators',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => '',
          'title_style' => 'h1',
        ),
        'type' => 'title_linked',
        'weight' => 3,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => '',
          'title_style' => 'h1',
        ),
        'type' => 'title_linked',
        'weight' => 3,
      ),
      'search_index' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'title',
        'settings' => array(
          'title_class' => '',
          'title_link' => 'content',
          'title_style' => 'h3',
        ),
        'type' => 'title_linked',
        'weight' => 13,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'name_field',
    'label' => 'Indicator name',
    'required' => 1,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'filtered_html' => 'filtered_html',
          'full_html' => 'full_html',
          'plain_text' => 'plain_text',
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'filtered_html' => array(
              'weight' => -9,
            ),
            'full_html' => array(
              'weight' => -10,
            ),
            'plain_text' => array(
              'weight' => -8,
            ),
          ),
        ),
      ),
      'entity_translation_sync' => FALSE,
      'hide_label' => array(
        'entity' => 0,
        'page' => 0,
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'taxonomy_term-observations-field_obstype'.
  $field_instances['taxonomy_term-observations-field_obstype'] = array(
    'bundle' => 'observations',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_obstype',
    'label' => 'Type',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Best value is');
  t('Catalog');
  t('Catalog description');
  t('Display this catalog\'s datasets');
  t('Enter a Topics term to classify your content. Those terms are in direct correlation with Agrovoc.');
  t('High means it is better to have a high value, low means the best value is the lowest one (like in rankings)');
  t('ID');
  t('Indicator description');
  t('Indicator name');
  t('Indicators menu');
  t('Land Book Indicators');
  t('Latest dataset');
  t('Maximun possible value of the indicator');
  t('Measurement unit');
  t('Measurement unit, like % or hectares');
  t('Minimun possible value of the indicator');
  t('Name');
  t('Observations');
  t('Organization');
  t('Overarching categories');
  t('Published dataset(s)');
  t('Related aside');
  t('Related blocks');
  t('Related concepts');
  t('Show indicators within the same catalog');
  t('The catalog this indicators it belongs to');
  t('The values for this indicator is taken from some controlled term list (could be characters, colors, strings, numbers...)
<a href="https://www.w3.org/TR/vocab-data-cube/#schemes">Read more</a>');
  t('Themes');
  t('Type');
  t('View parent');
  t('has Coded Value');
  t('max');
  t('min');
  t('view_indicators');

  return $field_instances;
}
