<?php
/**
 * Land Portal menus
 *
 * Author: Jules <jules@ker.bz>
 */

include_once 'landportal_menus.import.inc';

/**
 * Implementation of hook_menu_insert().
 */
// Should be call on each landportal-menu 'flush' / reload
function landportal_menus_menu_insert($menu) {
  landportal_menus_import_menu($menu);
  // menu_cache_clear_all();
  //landportal_menus_map_cts($menu);
}

function landportal_menus_map_cts() {
  if ($menu['menu_name'] != 'landportal-menu') return;
  $map = array(
    'landlibrary_resource' => 'library',
    'news' => 'news-events',
    'event' => 'news-events',
    'debate' => 'debate/debates',
    'blog_post' => 'news-events',
    'organization' => 'debate/community',
    'partners' => 'debate/community',
    'project' => 'debate/community',
    'dataset' => 'book/data',
    'landbook_country' => 'book/countries',
    'thematic_narrative' => 'book/thematic',
    'sdgi' => 'book/thematic', // @todo SDG cover + about page
  );
  //foreach(array('en', 'fr', 'es', 'pt') as $langcode) {
  foreach(array('en') as $langcode) {
    foreach($map as $ct => $path) {
      landportal_menus_bind_cts($ct, $path, $langcode);
    }
  }
}

function landportal_menus_bind_cts($ctype, $path, $langcode) {
  $q = db_select('url_alias', 'url');
  $q->join('menu_links', 'menu', 'menu.link_path = url.source AND menu.menu_name = :menun', array(':menun' => 'landportal-menu'));
  $q->fields('url', array('source'))
    ->fields('menu', array('mlid', 'plid'))
    ->condition('alias', $path)
    ->condition('url.language', $langcode);
  $result = $q->execute()
              ->fetchAssoc();
  print 'Remap ' .$langcode . ' / ' . $ctype . ' to ' . $ctype . ' ' . $result['mlid'] . "\n";
  if ($result && isset($result['mlid'])) {
    // create the array to populate the rule
    $rule = array(
      'admin_title' => 'CT ' . $ctype . ' ' . $langcode,
      'conditions' => array(
        'content_type' => array(
          'content_type' => array(
            $ctype => $ctype
          ),
        ),
      ),
      'menu_name' => 'landportal-menu',
      'plid' => $result['plid'],
      'mlid' => $result['mlid'],
    );
    if ($langcode != 'en' ) {
      $rule['language'] = array(
        'language' => array($langcode)
      );
    }
    //dpm($rule);
    //print_r($rule);
    // By calling menu_position_add_rule() here, we're assuming that this exact rule does not exist
    menu_position_add_rule($rule);
  }
}
