<?php
/**
 * @file
 * Code for the landportal SDGs feature.
 */

include_once 'landportal_sdgs.features.inc';

function landportal_sdgs_views_plugins_alter(&$plugins) {
  // Allow rows classes on BS accordion view
  $plugins['style']['views_bootstrap_accordion_plugin_style']['uses row class'] = TRUE;
  //dpm($plugins);
}

// Allow rows classes on BS accordion view
function landportal_sdgs_preprocess_views_bootstrap_accordion_plugin_style(&$vars) {
  foreach ($vars['rows'] as $key => $item) {
    $vars['row_classes'][$key] = array($vars['view']->style_plugin->get_row_class($key));
  }
}

/* function landportal_sdgs_XXXX() { */
/*   // */
/* } */

// Force view related block order
function landportal_sdgs_node_presave($node) {
  if ($node->type == 'sdgi' && array_key_exists(LANGUAGE_NONE, $node->field_related_blocks)) {
    if (is_array($node->field_related_blocks[LANGUAGE_NONE]) && count($node->field_related_blocks[LANGUAGE_NONE]) > 1) {
      $node->field_related_blocks[LANGUAGE_NONE] = array_reverse($node->field_related_blocks[LANGUAGE_NONE]);
    }
  }
}
