<?php
/**
 * @file
 * landportal_sdgs.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function landportal_sdgs_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '11.1 Housing',
    'description' => 'By 2030, ensure access for all to adequate, safe and affordable housing and basic services and upgrade slums',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '1e4fed5b-0b4c-4044-90a2-cfe15a5ff07c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 11.1,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'target',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '11.1 Housing',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8261-0',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e6afcb19-5d23-4416-919b-7e3ae972150e',
    ),
  );
  $terms[] = array(
    'name' => '2.4 Sustainable food',
    'description' => 'By 2030, ensure sustainable food production systems and implement resilient agricultural practices that increase productivity and production, that help maintain ecosystems, that strengthen capacity for adaptation to climate change, extreme weather, drought, flooding and other disasters and that progressively improve land and soil quality',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '237eb1bb-6cde-4370-b11c-fe715f48f993',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 2.4,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'target',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '2.4 Sustainable food',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8262-0',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'bf413a5b-e03f-4cf0-9a41-45b8075df7a1',
    ),
  );
  $terms[] = array(
    'name' => '11.7 Universal access',
    'description' => 'By 2030, provide universal access to safe, inclusive and accessible, green and public spaces, in particular for women and children, older persons and persons with disabilities',
    'format' => 'plain_text',
    'weight' => 2,
    'uuid' => '24b359a8-4e56-469f-bb34-1ac07c8e9b9a',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 11.7,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'target',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '11.7 Universal access',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8263-0',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e6afcb19-5d23-4416-919b-7e3ae972150e',
    ),
  );
  $terms[] = array(
    'name' => '5 Gender equality',
    'description' => 'Achieve gender equality and empower all women and girls',
    'format' => 'plain_text',
    'weight' => 7,
    'uuid' => '33aec81f-00ea-45da-ad09-5e8f11920cf0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 5,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'goal',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '5 Gender equality',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8264-0',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => '15.3 Restore degraded land and soil',
    'description' => 'By 2030, combat desertification, restore degraded land and soil, including land affected by desertification, drought and floods, and strive to achieve a land degradation-neutral world',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '439dbb02-9dea-489c-8912-9793b24cfcda',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 15.3,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'goal',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '15.3 Restore degraded land and soil',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8265-0',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e0b77041-b168-417e-93b4-7e7394043190',
    ),
  );
  $terms[] = array(
    'name' => '1.4 Equal rights',
    'description' => 'By 2030, ensure that all men and women, in particular the poor and the vulnerable, have equal rights to economic resources, as well as access to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '46907bb4-b4d8-40c8-9004-0cab02c289fe',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 1.4,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'target',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '1.4 Equal rights',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8266-0',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '56410748-9858-4d86-a99f-71654b33b21b',
    ),
  );
  $terms[] = array(
    'name' => '1 No poverty',
    'description' => 'End poverty in all its forms everywhere',
    'format' => 'plain_text',
    'weight' => 1,
    'uuid' => '56410748-9858-4d86-a99f-71654b33b21b',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'goal',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '1 No poverty',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8267-0',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => '15.1 Conservation and sustainable use',
    'description' => 'By 2020, ensure the conservation, restoration and sustainable use of terrestrial and inland freshwater ecosystems and their services, in particular forests, wetlands, mountains and drylands, in line with obligations under international agreements',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6aa2e871-4ea4-4464-9fdf-4a4ee21f9662',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 15.1,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'target',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '15.1 Conservation and sustainable use',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8268-0',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e0b77041-b168-417e-93b4-7e7394043190',
    ),
  );
  $terms[] = array(
    'name' => 'Tier 3',
    'description' => 'Indicator for which there are no established methodology and standards or methodology/standards are being developed/tested',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '981b7cc9-9559-4493-b07a-3fec1225640a',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs_tiers',
    'field_date' => array(
      'und' => array(
        0 => array(
          'value' => '2017-06-22 00:00:00',
          'value2' => '2017-06-22 00:00:00',
          'timezone' => 'Europe/Berlin',
          'timezone_db' => 'Europe/Berlin',
          'date_type' => 'datetime',
        ),
      ),
    ),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Undertake reforms',
    'description' => 'Undertake reforms to give women equal rights to economic resources, as well as access to ownership and control over land and other forms of property, financial services, inheritance and natural resources, in accordance with national laws',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ae439fb1-7608-44f4-ae45-29ee0111d666',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(),
    'field_image' => array(),
    'field_sdgs_type' => array(),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => 'Undertake reforms',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8270-0',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '33aec81f-00ea-45da-ad09-5e8f11920cf0',
    ),
  );
  $terms[] = array(
    'name' => 'Tier 2',
    'description' => 'Indicator conceptually clear, established methodology and standards available but data are not regularly produced by countries',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b8381b37-16f6-4c32-8622-cf8bce134430',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs_tiers',
    'field_date' => array(
      'und' => array(
        0 => array(
          'value' => '2017-06-22 00:00:00',
          'value2' => '2017-06-22 00:00:00',
          'timezone' => 'Europe/Berlin',
          'timezone_db' => 'Europe/Berlin',
          'date_type' => 'datetime',
        ),
      ),
    ),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => '2 Zero hunger',
    'description' => 'End hunger, achieve food security and improved nutrition and promote sustainable agriculture',
    'format' => 'plain_text',
    'weight' => 6,
    'uuid' => 'bf413a5b-e03f-4cf0-9a41-45b8075df7a1',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'goal',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '2 Zero hunger',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8272-0',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Tier 1',
    'description' => 'Indicator conceptually clear, established methodology and standards available and data regularly produced by countries',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ca682b36-0536-444d-9ad3-58ff30a3e0a6',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs_tiers',
    'field_date' => array(
      'und' => array(
        0 => array(
          'value' => '2017-06-22 00:00:00',
          'value2' => '2017-06-22 00:00:00',
          'timezone' => 'Europe/Berlin',
          'timezone_db' => 'Europe/Berlin',
          'date_type' => 'datetime',
        ),
      ),
    ),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => '11.3 Urbanization',
    'description' => 'By 2030, enhance inclusive and sustainable urbanization and capacity for participatory, integrated and sustainable human settlement planning and management in all countries',
    'format' => 'plain_text',
    'weight' => 4,
    'uuid' => 'de58ff7d-8ce4-4138-9f41-0c8b6ac4a278',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 11.3,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'target',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '11.3 Urbanization',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8274-0',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e6afcb19-5d23-4416-919b-7e3ae972150e',
    ),
  );
  $terms[] = array(
    'name' => '15 Life on land',
    'description' => 'Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss',
    'format' => 'plain_text',
    'weight' => 9,
    'uuid' => 'e0b77041-b168-417e-93b4-7e7394043190',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 15,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'goal',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '15 Life on land',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8275-0',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => '11 Sustainable cities and communities',
    'description' => 'Make cities and human settlements inclusive, safe, resilient and sustainable',
    'format' => 'plain_text',
    'weight' => 8,
    'uuid' => 'e6afcb19-5d23-4416-919b-7e3ae972150e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'sdgs',
    'field_id' => array(
      'und' => array(
        0 => array(
          'value' => 11,
          'format' => NULL,
        ),
      ),
    ),
    'field_image' => array(),
    'field_sdgs_type' => array(
      'und' => array(
        0 => array(
          'value' => 'goal',
        ),
      ),
    ),
    'name_field' => array(
      'und' => array(
        0 => array(
          'value' => '11 Sustainable cities and communities',
          'format' => NULL,
        ),
      ),
    ),
    'field_singledate' => array(),
    'translations' => array(
      'original' => NULL,
      'data' => array(),
    ),
    'entity_translation_handler_id' => 'taxonomy_term-sdgs-eid-8276-0',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
