<?php

function landbook_vis_table_indicators_block_info() {
  $blocks['indicators_block'] = array(
    'info' => t('Indicators Block'),
  );
  return $blocks;
}

function landbook_vis_table_indicators_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'indicators_block' :
          $block['content'] = landbook_vis_table_indicators_block_view_output();
          break;
    }
    return $block;
}

function landbook_vis_table_indicators_block_view_output(){
  $block = block_load('landbook_vis_table_indicators', 'indicators_block');
  return theme('indicators-block',array('title'=>$block->title));
}

function landbook_vis_table_indicators_theme($existing, $type, $theme, $path){
  return array(
    'indicators-block'  => array('template' => 'landbook-vis-table-indicators','data' => NULL),
  );
}

function landbook_vis_table_indicators_page_alter(&$page){
  $library_path = libraries_get_path('lbvis');
  drupal_add_js($library_path . '/js/lbvis.table.js');
  drupal_add_js(drupal_get_path('module', 'landbook_vis_table_indicators').'/main.js');
}