<?php
/**
 * @file
 * This module provide an interface to the landbook section of the Landportal.
 *
 * The Landportal landbook
 *
 * Drupal refactoring: Jules <jules@ker.bz>
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function landbook_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
}

/**
 * Implements hook_context_default_contexts().
 * Automatically load all contexts found in MODULE/contexts/*.inc
 */
function landbook_context_default_contexts() {
  $export = array();
  $path = drupal_get_path('module', 'landbook').'/contexts';
  $files = file_scan_directory($path, '/\.inc$/');
  foreach ($files as $filepath => $file) {
    $context = NULL;
    include_once $filepath;
    if ($context) {
      $export[$context->name] = $context;
    }
  }
  return $export;
}

/**
 * Land Book Views
 */
function landbook_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_views_default_views().
 * Automatically load all views found in MODULE/views/*.inc
 */
function landbook_views_default_views() {
  $export = array();
  $path = drupal_get_path('module', 'landbook').'/views';
  $files = file_scan_directory($path, '/\.inc$/');
  foreach ($files as $filepath => $file) {
    include_once $filepath;
    $export[$view->name] = $view;
  }
  return $export;
}

/**
 * Implements hook_theme().
 */
function landbook_menu() {
  $items = array();
  // Provide a basic Landbook Drupal main menu (main-menu) link
  $items['book'] = array(
    'title'           => 'Land Book',
    'menu_name'       => 'main-menu',
    'type'            => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'page callback'   => 'drupal_goto',
    'page arguments'  => array('book'),
  );
  $translatables['book'][] = t('Land Book');
  return $items;
}

/**
 * Implements hook_theme().
 */
function landbook_theme($existing, $type, $theme, $path) {
    $templates = drupal_find_theme_templates($existing, '.tpl.php', $path);
    return $templates;
}

/**
 * Implements hook_help().
 */
function landbook_help($path, $arg) {
  switch ($path) {
  case "admin/help#landbook":
    return '<p>' . t("Landbook section of the Landportal") . '</p>'
      . '<p>' . t("It provides differents menus, block, pages and hooks plus a few configuration pages"). '</p>'
        . '<p>' . t("The Landbook is composed of different modules: catalog, countries, indicators, regions, reuse, sources, widgets") . '</p>';
    break;
  }
}



//
// TODO: Cleanup
//
// Should be replaced by landportal_taxonomy_country_term_by_iso(?)
//  update functions using term->tid
function landbook_get_region_iso($iso){
  $tid = db_select('field_data_field_iso3', 't')
    ->fields('t', array('entity_id'))
    ->condition('t.field_iso3_value', $iso)
    ->condition('t.bundle', 'regions')
    ->execute()
    ->fetchField();
  return $tid;
}
