<?php
/**
 * Implements hook_theme().
 */
function landbook_vggt_theme($existing, $type, $theme, $path) {
  // Scan this directory for template files
  $templates = drupal_find_theme_templates($existing, '.tpl.php', $path);
  return $templates;
}

/* Declare VGGT block */
function landbook_vggt_block_info() {
  $blocks['vis_vggt'] = array(
    'info'      => t('View CODA: VGGT'),
    'status'    => TRUE,
    'region'    => 'content',
    'visibility'=> BLOCK_VISIBILITY_LISTED,
    'pages'     => "book/countries/*",
    'weight'    => 16
  );
  return $blocks;
}

/* Drupal administration form for block */
function landbook_vggt_block_configure($delta='') {
  if ($delta != 'vis_vggt') return ;
   $form = array(
     'text_body' => array(
       '#type'          => 'text_format',
       '#title'         => t('Landbook VGGT information'),
       '#default_value' => landbook_vggt_body()
     )
   );
   return $form;
}

/* function landbook_vggt_block_save($delta = '', $edit = array()) { */
/*   if ($delta != 'vis_vggt') return ; */
/*   variable_set('landbook_vggt', $edit['text_body']['value']); */
/* } */

/* VGGT block description (shown everytime the VGGT vis appears) */
function landbook_vggt_body() {
  return 'yo';
}

function landbook_vggt_block_view($delta = '') {
  if ($delta != 'vis_vggt') return ;

  $PATH = libraries_get_path('js-view-coda');
  $jsAttr = 'iso3: Drupal.settings.landbook.countryCode';
  $block = array();
  $block['subject'] = t('Voluntary Guidelines on the Responsible Governance of Tenure');
  $block['content'] = array(
    '#attached' => array(
      'library' => array(array('landbook_view_coda', 'lbvis.vggt')),
      'js' => array(array(
          'type' => 'inline',
          'data' => lbvc__js_ready('VGGT = new lbvisVGGT(LBV, {'.$jsAttr.', target: "#block-landbook-vggt-vis-vggt"}); VGGT.init();')
        )
      )
    ),
    '#markup' => landbook_vggt_body()
  );
  return $block;
}
