<?php

/* Declare VGGT block */
function landbook_vggt_block_info() {
  $blocks['vis_vggt'] = array(
    'info'      => t('View CODA: VGGT'),
    'status'    => TRUE,
    'region'    => 'content',
    'visibility'=> BLOCK_VISIBILITY_LISTED,
    'pages'     => "book/countries/*",
    'weight'    => 16
  );
  return $blocks;
}


/* Drupal administration form for block */
function landbook_vggt_block_configure($delta='') {
  if ($delta != 'vis_vggt') return ;
   $form = array(
     'text_body' => array(
       '#type'          => 'text_format',
       '#title'         => t('Landbook VGGT information'),
       '#default_value' => landbook_vggt_body()
     )
   );
   return $form;
}

function landbook_vggt_block_save($delta = '', $edit = array()) {
  if ($delta != 'vis_vggt') return ;
  variable_set('landbook_vggt', $edit['text_body']['value']);
}

/* VGGT block description (shown everytime the VGGT vis appears) */
function landbook_vggt_body() {
  $vggtDesc = variable_get('landbook_vggt', '
                  <p>The Voluntary Guidelines on the Responsible Governance of Tenure of Land, Fisheries, and Forests in the
              Context of National Food Security (The VGGTs) were
                <a href="http://www.fao.org/docrep/016/i2801e/i2801e.pdf">endorsed by the Committee on World Food Security in 2012</a>.</p>
              <p>The "VGGT indicators" were created by Nicholas K. Tagliarino, PhD Candidate at the University of Groningen. (IND-NKT-VGGT). The indicators assess national laws against Section 16 of the VGGT standards on expropriation, compensation, and resettlement.</p>
                  <p>Each indicator relates to a principle established in the VGGTs.</p>
                  <ul>
                    <li>A (green)= National laws fully adopt the VGGT principle</li>
                    <li>B (yellow)= National laws partially adopt the VGGT principle</li>
                    <li>C (red)= National laws do not adopt the VGGT principle</li>
                  </ul>

              <p>Answering the questions posed by these indicators entails analyzing a broad range of national-level laws, including national constitutions, land acquisition acts, land acts, community land acts, agricultural land acts, land use regulations, and some court decisions.</p>');
    return $vggtDesc;
}

function landbook_vggt_block_view($delta = '') {
  if ($delta != 'vis_vggt') return ;

  $PATH = libraries_get_path('js-view-coda');
  $jsAttr = 'jsonPath: "' . $PATH . '/examples/json", iso3: Drupal.settings.landbook.countryCode';
    $block = array();
    $block['subject'] = t('Voluntary Guidelines on the Responsible Governance of Tenure');
    $block['content'] = array(
      '#attached' => array(
        'library' => array(
          array('landbook_view_coda', 'lbvis.vggt')
        ),
        'js' => array(
          array(
            'type' => 'inline',
            'data' => lbvc__js_ready('VGGT = new lbvisVGGT(LBV, {'.$jsAttr.', target: "#block-landbook-vggt-vis-vggt"}); VGGT.init();')
          )
        )
      ),
      '#markup' => landbook_vggt_body()
    );
    return $block;
}
